name: Cron Daily

on:
  schedule:
    - cron: '0 14 * * 1-5'
  workflow_dispatch:

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.14.6'
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run Crawler Script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          APP_ENV: ${{ secrets.APP_ENV }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
          WHATSAPP_URL: ${{ secrets.WHATSAPP_URL }}
          WHATSAPP_TOKEN: ${{ secrets.WHATSAPP_TOKEN }}
          WHATSAPP_NUMBER: ${{ secrets.WHATSAPP_NUMBER }}

        run: python main.py